accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login_check, name="login"),
    path("logout/", views.logout, name="logout"),
    path(
        "create_friend_request/",
        views.create_friend_request,
        name="create_friend_request",
    ),
    path(
        "accept_friend_request/",
        views.accept_friend_request,
        name="accept_friend_request",
    ),
]

bookmark_friends/urls.py
from django.urls import path
from . import views

app_name = "bookmark_friends"
urlpatterns = [
    path("", views.bookmark_friends_list, name="bookmark_friends_list"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.shortcuts import redirect

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("post/", include("post.urls", namespace="post")),
    path("", lambda r: redirect("post:post_list"), name="root"),
    path(
        "bookmark_friends/",
        include("bookmark_friends.urls", namespace="bookmark_friends"),
    ),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from . import views

app_name = "post"

urlpatterns = [
    path("", views.post_list, name="post_list"),
    path("explore/tags/<tag>/", views.post_list, name="post_search"),
    path("new/", views.post_new, name="post_new"),
    path("edit/<int:pk>/", views.post_edit, name="post_edit"),
    path("delete/<int:pk>/", views.post_delete, name="post_delete"),
    path("like/", views.post_like, name="post_like"),
    path("bookmark/", views.post_bookmark, name="post_bookmark"),
    path("comment/new/", views.comment_new, name="comment_new"),
    path("comment/delete/", views.comment_delete, name="comment_delete"),
]

post/models.py
from django.db import models
from accounts.models import *
from django.conf import settings
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
import re


def photo_path(instance, filename):
    from time import strftime
    from random import choice
    import string

    arr = [choice(string.ascii_letters) for _ in range(8)]
    pid = "".join(arr)
    extension = filename.split(".")[-1]
    return "{}/{}/{}.{}".format(
        strftime("post/%Y/%m/%d/"), instance.author.username, pid, extension
    )


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    photo = ProcessedImageField(
        upload_to=photo_path,
        processors=[ResizeToFill(600, 600)],
        format="JPEG",
        options={"quality": 90},
    )
    content = models.CharField(max_length=140, help_text="최대 140자 입력 가능")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    tag_set = models.ManyToManyField("Tag", blank=True)
    like_user_set = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        blank=True,
        related_name="like_post_set",
        through="Like",
    )
    bookmark_user_set = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        blank=True,
        related_name="bookmark_post_set",
        through="Bookmark",
    )

    class Meta:
        ordering = ["-created_at"]  # 👈 생성된 날짜 역순으로 정렬

    # HashTga 단어 찾는 매서드
    def tag_save(self):
        tags = re.findall(r"#(\w+)\b", self.content)
        if not tags:
            return
        for t in tags:
            tag, tag_created = Tag.objects.get_or_create(name=t)
            self.tag_set.add(tag)

    @property
    def like_count(self):
        return self.like_user_set.count()

    @property
    def bookmark_count(self):
        return self.bookmark_user_set.count()

    def __str__(self):
        return self.content


class Tag(models.Model):
    name = models.CharField(max_length=140, unique=True)

    def __str__(self):
        return self.name


class Like(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ("user", "post")  # 👈 class 전체의 규칙('user', 'post'는 unique)


class Bookmark(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ("user", "post")  # 👈 class 전체의 규칙('user', 'post'는 unique)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comment_set")
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=40)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-id"]

    def __str__(self):
        return self.content

post/forms.py
from django import forms
from .models import Comment, Post


class CommentForm(forms.ModelForm):
    content = forms.CharField(
        label="",
        widget=forms.TextInput(
            attrs={"size": "70px", "placeholder": "댓글 달기...", "maxlength": "40"}
        ),
    )

    class Meta:
        model = Comment
        fields = ["content"]


class PostForm(forms.ModelForm):
    photo = forms.ImageField(label="", required=False)
    content = forms.CharField(
        label="",
        widget=forms.Textarea(
            attrs={
                "class": "post-new-content",
                "rows": 5,
                "cols": 50,
                "placeholder": "무슨 생각을 하시나요?(140자 가능)",
            }
        ),
    )

    class Meta:
        model = Post
        fields = ["photo", "content"]

post/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth import get_user_model
from .models import *
from .forms import CommentForm, PostForm
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
import json
from django.contrib import messages
from django.db.models import Count  # 👈 'Count' import
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage


# Create your views here.
def post_list(request, tag=None):  # 👈 tag가 url을 통해 전달되지 않을때는 None값 할당
    tag_all = Tag.objects.annotate(num_post=Count("post")).order_by(
        "-num_post"
    )  # 👈 모든 태그를 정렬하여 가져옵니다.
    if tag:
        post_list = Post.objects.filter(
            tag_set__name__iexact=tag
        )  # 👈 Tag의 이름과 정확히 일치하는 Post를 가져옵니다
    else:
        post_list = Post.objects.all()  # 👈 argument로 들어온 tag가 없다면, 모두를 출력
    if request.method == "POST":
        tag = request.POST.get("tag")
        tag_clean = "".join(e for e in tag if e.isalnum())  # 👈 숫자나 문자열로 들어왔을 때, 작동
        return redirect("post:post_search", tag_clean)

    comment_form = CommentForm()

    # Paginaion
    paginator = Paginator(post_list, 3)
    page_num = request.POST.get("page")
    try:
        posts = paginator.page(page_num)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    if request.is_ajax():
        return render(
            request,
            "post/post_list_ajax.html",
            {
                "posts": posts,
                "comment_form": comment_form,
            },
        )

    if request.user.is_authenticated:
        username = request.user
        friends = username.friends.all()
        request_friends = username.friend_requests
        user = get_object_or_404(get_user_model(), username=username)
        user_profile = user.profile
        friend_list = user.friends.all()
        my_friend_user_list = list(map(lambda friend: friend.user, friend_list))
        friend_request_list = user.friend_requests.all()
        my_friend_request_user_list = list(
            map(lambda friend_request: friend_request.to_user, friend_request_list)
        )
        return render(
            request,
            "post/post_list.html",
            {
                "tag": tag,
                "tag_all": tag_all,
                "user_profile": user_profile,
                "posts": post_list,
                "friends": friends,
                "request_friends": request_friends,
                "my_friend_user_list": my_friend_user_list,
                "my_friend_request_user_list": my_friend_request_user_list,
                "comment_form": comment_form,
            },
        )
    else:
        return render(
            request,
            "post/post_list.html",
            {
                "tag": tag,
                "tag_all": tag_all,
                "posts": post_list,
                "comment_form": comment_form,
            },
        )


@login_required  # 👈 login이 된 상태에서만 아래 함수를 작동시켜요:)
@require_POST  # 👈 POST 방식으로만 값을 받을 수 있어요:)
def post_like(request):
    pk = request.POST.get("pk", None)  # 👈 게시글의 pk값을 가져옵니다.
    post = get_object_or_404(Post, pk=pk)  # 👈 pk값으로 게시글의 Object를 가져옵니다.
    post_like, post_like_created = post.like_set.get_or_create(user=request.user)

    if not post_like_created:  # 👈 생성된 좋아요가 이미 있다면,
        post_like.delete()  # 👈 post_like 삭제
        message = "좋아요 취소"
    else:  # 👈 생성된 좋아요가 없어서 생성되었다면,
        message = "좋아요"

    context = {"like_count": post.like_count, "message": message}

    return HttpResponse(json.dumps(context), content_type="application/json")


@login_required
@require_POST
def post_bookmark(request):
    pk = request.POST.get("pk", None)
    post = get_object_or_404(Post, pk=pk)
    post_bookmark, post_bookmark_created = post.bookmark_set.get_or_create(
        user=request.user
    )

    if not post_bookmark_created:  # 👈 북마크가 되어있다면,
        post_bookmark.delete()  # 👈 북마크 Object 삭제
        message = "북마크 취소"
        is_bookmarked = "N"  # 👈 is_bookmarked에 N을 담음
    else:
        message = "북마크"
        is_bookmarked = "Y"  # 👈 is_bookmarked에 Y을 담음

    context = {"is_bookmarked": is_bookmarked, "message": message}

    return HttpResponse(json.dumps(context), content_type="application/json")


@login_required
def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            post.tag_save()
            messages.info(request, "새 글이 등록되었습니다")
            return redirect("post:post_list")
    else:
        form = PostForm()
    return redirect("post:post_list")


@login_required
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if post.author != request.user:
        messages.warning(request, "잘못된 접근입니다")
        return redirect("post:post_list")

    if request.method == "POST":
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save()
            post.tag_set.clear()
            post.tag_save()
            messages.success(request, "수정완료")
            return redirect("post:post_list")
    else:
        form = PostForm(instance=post)
    return render(
        request,
        "post/post_edit.html",
        {
            "post": post,
            "form": form,
        },
    )


@login_required
def post_delete(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if post.author != request.user or request.method == "GET":
        messages.warning(request, "잘못된 접근입니다")
        return redirect("post:post_list")

    if request.method == "POST":
        post.delete()
        return redirect("post:post_list")


@login_required
def comment_new(request):
    pk = request.POST.get("pk")  # 👈 pk값
    post = get_object_or_404(Post, pk=pk)  # 👈 pk값으로 Post Object 가져옴
    if request.method == "POST":
        form = CommentForm(request.POST)  # 👈 form의 입력 정보를 CommentForm에 전달
        if form.is_valid():  # 👈 유효성 검사
            comment = form.save(commit=False)  # 👈 저장 가로채기
            comment.author = request.user
            comment.post = post
            comment.save()  # 👈 Object 저장
            return render(
                request,
                "post/comment_new_ajax.html",
                {
                    "comment": comment,
                },
            )
    return redirect("post:post_list")  # 👈 post_list 다시 호출


@login_required
def comment_delete(request):
    pk = request.POST.get("pk")  # 👈 pk값
    comment = get_object_or_404(Comment, pk=pk)  # 👈 Comment Object 가져옴
    if request.method == "POST" and request.user == comment.author:
        comment.delete()
        message = "삭제완료"
        status = 1
    else:
        message = "잘못된 접근입니다"
        status = 0

    return HttpResponse(
        json.dumps({"message": message, "status": status}),
        content_type="application/json",
    )

post/templates/post/comment_new_ajax.html
<div class="comment-detail" id="comment{{ comment.id }}">
    <div class="id">
        <div class="profile_img"><img src="{{ comment.author.profile.picture.url }}" alt=""></div>
        <div class="comment_field">
            <div class="text_container">
                <div class="name">{{ comment.author.profile.nickname }}</div>
                <div class="text_field">{{ comment.content }}</div>
                <div class="time">{{ comment.created_at|timesince }}</div>
            </div>
        </div>
        {% if user == comment.author %}
        <input type="button" class="delete" data-name="comment_delete" value="X" name="{{ comment.id }}">
        {% endif %}
    </div>
</div>

post/templates/post/layout.html
{% extends 'layout.html' %}

post/templates/post/post_edit.html
{% extends "post/layout.html" %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/edit.css' %}">
{% endblock %}

{% block content %}
<div id="edit_contanier">
    <div class="post_form_container">
        <form action="#" class="post_form" method="post" enctype="multipart/form-data">
            <div class="title">
                Edit Post
            </div>

            <div class="preview">
                <div class="upload">
                    <div class="post_btn">
                        {% if post %}
                            <p><img id="img_id" src="{{ post.photo.url }}" alt="" style="width: 300px; height: 300px; object-fit: cover"></p>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="submit_btn" value="수정완료">
        </form>
    </div>
</div>

<script>
    const photo = docuemnt.querySelector('#img_id');
    document.querySelector('#photo-clear_id').remove();
    document.querySelector("label[for='photo-clear_id']").remove();
    function upload_img(input) {
        var reader = new FileReader();
        if (input.files && input.files[0]){
            reader.onload = function (e) {
                photo.setAttribute('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }
    let idPhoto = document.querySelector('#id_photo');
    idPhoto.addEventListener('change', function(){
        upload_img(this)
    })
</script>

{% endblock %}

post/templates/post/post_list_ajax.html
{% load static %}
{% load post_extras %}
{% for post in posts %}
<article class="contents">
    <header>
        <div class="profile_container">
            <div class="profile_img"><img src="{{ post.author.profile.picture.url }}" alt=""></div>
            <div>
                <div class="name">{{ post.author.profile.nickname }}</div>
                <div class="time">{{ post.updated_at|timesince }}</div>
            </div>
            <div class="more" data-name="more">
                <span class="icon--more"></span>
                <ul class="hidden_menu">
                {% if user in post.bookmark_user_set.all %}
                    <li class="bookmark" data-name="bookmark" name="{{ post.id }}">저장됨</li>
                {% else %}
                    <li class="bookmark" data-name="bookmark" name="{{ post.id }}">저장하기</li>
                {% endif %}
                
                {% if post.author in my_friend_user_list %}
                {% elif post.author in my_friend_request_user_list %}
                    <li>친구요청중</li>
                {% else %}
                    <li><button class="friend_request" data-name="friend_request" name="{{ post.author.profile.user.id }}">친구요청하기</button></li>
                {% endif %}
                {% if post.author == user %}
                    <li><a href="{% url 'post:post_edit' post.pk %}">수정</a></li>
                    <li>
                        <form action="{% url 'post:post_delete' post.pk %}" method="post">
                            {% csrf_token %}
                            <input type="submit" class="post-delete" value="삭제">
                        </form>                                            
                    </li>
                    {% endif %}    
                </ul>
            </div>
        </div>
    </header>
    <div class="main_article">
        {{ post|add_link|safe|linebreaksbr }}
    </div>
    <div class="img_section"><img src="{{post.photo.url}}" alt=""></div>
    <div class="ajax_field">
        <div class="like">좋아요<span class="like_count" id="like-count-{{post.id}}">{{post.like_count}}</span>개</div>
        <div class="comment">댓글<span class="comment_count" id="comment-count-{{ post.id }}">{{ post.comment_set.count }}</span>개</div>
    </div>
    <div class="btn_container">
    {% if user in post.like_user_set.all %}
        <div class="like-btn active" name="{{ post.id }}" data-name="heartbeat"><span class="icon icon--like-line"></span>좋아요</div>
    {% else %}
        <div class="like-btn" name="{{ post.id }}" data-name="heartbeat"><span class="icon icon--like-line"></span>좋아요</div>
    {% endif %}
        <div class="comment-btn"><span class="icon icon--cooment-line"></span>댓글</div>
    </div>

    <div class="comment_container">
        <div class="comment" id="comment-list-ajax-post{{ post.id }}">
            {% for comment in post.comment_set.all %}
            <div class="comment-detail" id="comment{{ comment.id }}">
                <div class="id">
                    <div class="profile_img"><img src="{{ comment.author.profile.picture.url }}" alt=""></div>
                    <div class="comment_field">
                        <div class="text_container">
                            <div class="name">{{ comment.author.profile.nickname }}</div>
                            <div class="text_field">{{ comment.content }}</div>
                            <div class="time">{{ comment.created_at|timesince }}</div>
                        </div>
                    </div>
                    {% if user == comment.author %}
                    <input type="button" class="delete" data-name="comment_delete" value="X" name="{{ comment.id }}">
                    {% endif %}                                             
                </div>
            </div>
            {% endfor %}
        </div>
    </div>

    <div class="comment_input" id="add-comment-post{{post.id}}">
        {% if user.is_authenticated %}
            <div class="profile_img"><img src="{{ user_profile.picture.url }}" alt=""></div>
            <div class="input_container">
                {{ comment_form }}
                <button class="send">
                    <span class="icon--send" name="{{ post.id }}" data-name="comment"></span>
                </button>
            </div>

        {% else %}
            <div class="profile_img"><img src="{% static 'imgs/noun_User.png' %}" alt=""></div>
            <div class="input_container">
                {{ comment_form }}
                <button class="send">
                    <span class="icon--send" name="{{ post.id }}" data-name="comment" onclick="alert('댓글을 작성하려면 로그인이 필요합니다')"></span>
                </button>
            </div>
        {% endif %}                            
    </div>
</article>
{% endfor %}

post/templates/post/script_ajax.html
<script type="text/javascript">
    (function(){ // 👈 익명 함수
        const delegation = document.querySelector('#contents_container');
        const textField = document.querySelector('#text_field');

        function delegationFunc(e) {
        let elem = e.target; // 👈 click 위치
        
        while (!elem.getAttribute('data-name')){ // elem이 "data-name"을 포함하고 있으면 아래 반복
            elem = elem.parentNode;  // 부모 node를 계속 찾아올라감

            if (elem.nodeName === 'BODY'){ // elem이 'BODY' 태그를 만다면,

                elem = null;
                return; // 종료
            }
        }
        // Like Btn Ajax 통신
        if (elem.matches('[data-name="heartbeat"]')){ // 👈 elem의 내용 중에 [data-name="heartbeat"]이 있다면,,
            const pk = elem.getAttribute('name'); // 👈 게시글의 id값을 가져옵니다. = post.pk 
            // ajax 통신 방법
            $.ajax({
                type: "POST", // 👈 POST 방식
                url: "{% url 'post:post_like' %}", // 👈 url 경로
                data: {'pk': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}'}, // 👈 pk값과, csrf_token 전달
                dataType: "json", // // 👈 json 방식 선택
                success: function (response){  // 👈 성공햇을 때,,
                    const likeCount = document.querySelector('#like-count-'+pk); // 좋아요 갯수를 count하는 부분을 추출한 뒤,
                    likeCount.innerHTML = response.like_count; // like_count를 html에 넣어줍니다.
                },
                error: function (request, status, error){  // 👈 실패했을 때,,
                    console.log("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
                }
            });
        }
        // Bookmark Btn Ajax 통신
        if (elem.matches('[data-name="bookmark"]')){ // data-name이 "bookmark"라면,
            // console.log('북마크');
            const pk = elem.getAttribute('name'); // 해당 요소에서 name값을 가져옴
            // console.log(pk);
            $.ajax({
                type: "POST",
                url: "{% url 'post:post_bookmark' %}",
                data: {'pk': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}' },
                dataType: "json",
                success: function (response){ // 성공햇을 때, response 값을 돌려 받고
                    // 템플릿 Text 변경
                    let btn_bookmark_text = ""; // 빈칸인 상수 생성
                    if(response.is_bookmarked === 'N'){
                        btn_bookmark_text = "저장하기";
                    } else if (response.is_bookmarked === 'Y') {
                        btn_bookmark_text = "저장됨";
                    }
                    const bookmark = document.querySelector('.bookmark').innerHTML = btn_bookmark_text;
                },
                error: function (reqeust, status, error){ // 실패했을 때, reqeust, status, errorr 값을 받음
                    console.log("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
                }
            })
        }
        // 친구 요청 Ajax 통신
        if (elem.matches('[data-name="friend_request"]')){
            const user_id = elem.getAttribute('name');
            $.ajax({
                type: "POST",
                url: "{% url 'accounts:create_friend_request' %}",
                data: {
                    'pk': user_id,
                    'csrfmiddlewaretoken': '{{ csrf_token }}',
                },
                dataType: "json",
                success: function(response){
                    elem.innerHTML = "친구요청중";
                },
            })
        }
        // 댓글 생성 ajax 통신
        if (elem.matches('[data-name="comment"]')){
            console.log('새댓글')
            const pk = elem.getAttribute('name'); // pk값 가져오기
            const content = document.querySelector('#add-comment-post'+pk+'>div>input[type=text]').value; // 댓글 내용 가져오기
            if(content.length > 140) {
                alert("댓글은 최대 140자 입력 가능하빈다. 현재 글자수: "+ content.length);
                return;
            }
            if(content.length == 0) {
                alert("글자를 입력해 주세요: "+ content.length);
                return;
            }
            $.ajax({
                type: "POST",
                url: "{% url 'post:comment_new' %}",
                data: {
                    'pk': pk,
                    'content': content,
                    'csrfmiddlewaretoken': '{{ csrf_token }}',
                },
                dataType: "html",
                success: function(data, textStatus, jqXHR){
                    document.querySelector("#comment-list-ajax-post"+pk).insertAdjacentHTML("afterbegin", data);
                    location.reload();
                }
            })
        }
        // 댓글 삭제 ajax 통신
        if (elem.matches('[data-name="comment_delete"]')){
            console.log('삭제')
            const pk = elem.getAttribute('name');

            $.ajax({
                type: "POST",
                url: "{% url 'post:comment_delete' %}",
                data: {
                    'pk': pk,
                    'csrfmiddlewaretoken': '{{ csrf_token }}',
                },
                dataType: "json",
                success: function(response){
                    if(response.status){
                        document.querySelector('#comment'+pk).remove();
                        location.reload();
                    }
                }
            })

        }
        // 게시물 생성창 크기 조절 ajax
        if(elem.matches('[data-name="add"]')){
            console.log('글추가')
            textField.style.height = '100px';
            submit.disabled = false;
            submit.parentNode.style.display = 'block';
        }
        elem.classList.toggle('active');
    };

    function scrollfunc(){
        const scrollHeight = pageYOffset + window.innerHeight;
        const documentHeight = document.body.scrollHeight;

        if(scrollHeight >= documentHeight){
            const page = document.querySelector('#page').value;
            // console.log(page);
            const end_page = {{posts.paginator.num_pages}}
            if (page > end_page){
                return;
            }
            document.querySelector('#page').value = parseInt(page) + 1;
            callMorePostAjax(page);
        }
    }
    
    function callMorePostAjax(page){
        const end_page = {{posts.paginator.num_pages}};
        if (page > end_page){
            return;
        }
        $.ajax({
            type : "POST",
            url : "{% url 'post:post_list' %}",
            data : {
                'page' : page,
                'csrfmiddlewaretoken' : "{{csrf_token}}",
            },
            dataType : 'html',
            success : addMorePostAjax,
        })
    }

    function addMorePostAjax(data, textStatus, jqXHR){
        let post = document.querySelector('#post_list_ajax');
        post.insertAdjacentHTML("beforeend", data);
    }


    window.addEventListener('scroll', scrollfunc);
    delegation.addEventListener('click', delegationFunc); // 👈 '#contents_container'가 클릭됬을 때, delegationFunc실행
})();
</script> 