accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login_check, name="login"),
    path("logout/", views.logout, name="logout"),
    path(
        "create_friend_request/",
        views.create_friend_request,
        name="create_friend_request",
    ),
    path(
        "accept_friend_request/",
        views.accept_friend_request,
        name="accept_friend_request",
    ),
]

bookmark_friends/urls.py
from django.urls import path
from . import views

app_name = "bookmark_friends"
urlpatterns = [
    path("", views.bookmark_friends_list, name="bookmark_friends_list"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.shortcuts import redirect

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("post/", include("post.urls", namespace="post")),
    path("", lambda r: redirect("post:post_list"), name="root"),
    path(
        "bookmark_friends/",
        include("bookmark_friends.urls", namespace="bookmark_friends"),
    ),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from . import views

app_name = "post"

urlpatterns = [
    path("", views.post_list, name="post_list"),
    path("explore/tags/<tag>/", views.post_list, name="post_search"),
    path("new/", views.post_new, name="post_new"),
    path("edit/<int:pk>/", views.post_edit, name="post_edit"),
    path("delete/<int:pk>/", views.post_delete, name="post_delete"),
    path("like/", views.post_like, name="post_like"),
    path("bookmark/", views.post_bookmark, name="post_bookmark"),
    path("comment/new/", views.comment_new, name="comment_new"),
    path("comment/delete/", views.comment_delete, name="comment_delete"),
]

bookmark_friends/models.py
from django.db import models

bookmark_friends/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth import get_user_model
from post.models import *


def bookmark_friends_list(request):
    username = request.user
    user = get_object_or_404(get_user_model(), username=username)
    user_profile = user.profile
    friend_requests = user.requested_friend_requests.all()
    friends = username.friends.all()
    post_list = Post.objects.all()
    context = {
        "user_profile": user_profile,
        "post_list": post_list,
        "friend_requests": friend_requests,
        "friends": friends,
    }
    return render(
        request,
        "bookmark_friends/bookmark_friends_list.html",
        context,
    )

bookmark_friends/templates/bookmark_friends/bookmark_friends_list.html
{% extends 'layout.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/save.css' %}">
{% endblock %}

{% block content %}
<div id="wrapper">
    <div class="inner">
        <div class="left_box">
            <div class="my_name">
                <div><span class="icon icon--save"></span><span clss="icon--more"></span></div>
                <span class="name">저장됨 & 친구목록</span>
                <span class="icon--more"></span>
            </div>
            <ul class="list">
                <li class="active"><a href="#" data-name="save"><span class="icon icon--save"></span>저장됨<span class="icon--more"></span></a></li>
                <li><a href="#" data-name="friends"><span class="icon icon--messenger"></span>친구목록<span class="icon--more"></span></a></li>
            </ul>
        </div>

        <section id="contents_container">
            <div id="save">
                {% for post in post_list %}
                    {% for bookmark_user in post.bookmark_user_set.all %}    
                        {% if user == bookmark_user.profile.user %}
                            <article class="contents">
                                <div class="thumbnail"><img src="{{ post.photo.url }}" alt=""></div>
                                <div>
                                    <h1 class="heading">{{ post.author.username }}님의 글입니다 </h1>
                                    <p class="description">
                                        {{ post.content }}
                                    </p>
                                </div>
                            </article>            
                        {% endif %}
                    {% endfor %}
                {% endfor %}
            </div>

            <div id="friends" class="hidden">
                {% for friend_request in friend_requests %}
                <article class="contents">
                    <div class="thumbnail"><img src="{{ friend_request.from_user.profile.picture.url }}" alt=""></div>
                    <div class="right_contents">
                        <h1 clsss="heading">{{ friend_request.from_user.username }}님이 친구요청을 보냈습니다 </h1>
                        <div class="btn_container">
                            <button class="agree" data-name="friend_accept" name="{{ friend_request.id }}">수락</button>
                        </div>       
                    </div>
                </article>
                {% endfor %}

                {% for friend in friends %}
                <article class="contents">
                    <div class="thumbnail"><img src="{{ friend.user.profile.picture.url }}" alt=""></div>
                    <div class="right_contents">
                        <h1 clsss="heading">{{ friend.user }}님</h1>
                    </div>
                </article>
                {% endfor %}
            </div>

        </section>
    </div>
</div>

<div id="side_box">
    <ul>
        {% for friend in friends %}        
            <li>
                <div class="profile_img"><img src="{{ friend.user.profile.picture.url }}" alt=""></div>
                <div class="name">{{ friend.user }}</div>
                <div class="light"></div>
            </li>
        {% endfor %}
    </ul>
</div>

<script>
    const friends = document.querySelector('#contents_container')
    function delegationFunc(e){
        let elem = e.target
        console.log(elem);
        while (!elem.getAttribute('data-name')){
            elem = elem.parentNode;
            if (elem.nodeName == 'BODY'){
                elem = null;
                return;
            }
        }

        if (elem.matches('[data-name="friend_accept"]')){
            const request_id = elem.getAttribute('name');
            $.ajax({
                type: "POST",
                url: "{% url 'accounts:accept_friend_request' %}",
                data: {
                    'pk': request_id,
                    'csrfmiddlewaretoken': '{{ csrf_token }}',
                },
                dataType: "json",
                success: function(response){
                    location.reload();
                },
            })
        }
    }
    friends.addEventListener('click', delegationFunc);
</script>

{% endblock %}

{% block js %}
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="{% static 'js/save.js' %}"></script>
{% endblock %}

bookmark_friends/templates/bookmark_friends/layout.html
{% extends 'laytout.html' %} 