accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("signup/", views.signup, name="signup"),
    path("login/", views.login_check, name="login"),
    path("logout/", views.logout, name="logout"),
    path(
        "create_friend_request/",
        views.create_friend_request,
        name="create_friend_request",
    ),
    path(
        "accept_friend_request/",
        views.accept_friend_request,
        name="accept_friend_request",
    ),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.shortcuts import redirect

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("post/", include("post.urls", namespace="post")),
    path("", lambda r: redirect("post:post_list"), name="root"),
    path(
        "bookmark_friends/",
        include("bookmark_friends.urls", namespace="bookmark_friends"),
    ),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from . import views

app_name = "post"

urlpatterns = [
    path("", views.post_list, name="post_list"),
    path("explore/tags/<tag>/", views.post_list, name="post_search"),
    path("new/", views.post_new, name="post_new"),
    path("edit/<int:pk>/", views.post_edit, name="post_edit"),
    path("delete/<int:pk>/", views.post_delete, name="post_delete"),
    path("like/", views.post_like, name="post_like"),
    path("bookmark/", views.post_bookmark, name="post_bookmark"),
    path("comment/new/", views.comment_new, name="comment_new"),
    path("comment/delete/", views.comment_delete, name="comment_delete"),
]

config/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="ko-KR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <title>Facebook</title>
    <link rel="shortcut icon" href="{% static 'imgs/favicon.png' %}">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">    
    <link rel="stylesheet" href="{% static 'css/common.css' %}">    
    {% block head %}
    {% endblock %}
</head>
<body>
    <section id="container">
        <header id="header">
            <div class="inner">

                <div class="left">
                    <h1 class="icon icon--facebook-white"><a href="{% url 'post:post_list' %}"></a></h1>

                    <div class="search_container">
                        <form action="#">
                            {% csrf_token %}
                            <input type="text" name="tag" id="search_box" placeholder="검색" required>
                            <button type="submit"><span class="icon--search-black"></span></button>
                        </form>
                    </div>
                </div>

                <div class="right">
                {% if user_profile %}

                <div><a href="{% url 'accounts:logout' %}" class="logout">로그아웃</a></div>
                <div class="my_name"><span class="profile_img"><img src="{{ user_profile.picture.url }}" alt=""></span><a href="#">{{ user_profile.nickname }}</a></div>
                <div class="home"><a href="{% url 'post:post_list' %}">홈</a></div>
                <div class="people"><a href="#"><span class="icon icon--people-black"></span></a></div>
                <div class="bell"><span class="icon icon--bell-black"></span></div>
                <div><a href="#"><span class="icon icon--messenger--black"></span></a></div>
                <div><a href="#"><span class="icon icon--chart--black"></span></a></div>
                <div class="question"><a href="#"><span class="icon icon--question-black"></span></a></div>

                {% else %}

                <div><a href="{% url 'accounts:login' %}">로그인</a></div>
                <div class="my_name"><span class="profile_img"><img src="{% static 'imgs/noun_User.png' %}" alt=""></span><a href="#"></a></div>
                <div class="home"><a href="{% url 'post:post_list' %}">홈</a></div>
                <div class="people"><a href="#"><span class="icon icon--people-black"></span></a></div>
                <div class="bell"><span class="icon icon--bell-black"></span></div>
                <div><a href="#"><span class="icon icon--messenger--black"></span></a></div>
                <div><a href="#"><span class="icon icon--chart--black"></span></a></div>
                <div class="question"><a href="#"><span class="icon icon--question-black"></span></a></div>

                {% endif%}
                </div> 
            </div>
        </header>
        {% block content %}
        {% endblock %}

        {% block js %}
        {% endblock %}    
    </section> 
</body>
</html>